version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: media_pipeline_db
    env_file:
      - config/db.env
    ports:
      - "5432:5432"
    volumes:
      - media_pipeline_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  media_pipeline_db:
    name: media_pipeline_db
